// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8x5hfCivqXC6J5RL7cWhAGohrXOtztSU',
    appId: '1:72940076040:web:09f5f7d4b31bc62d7de5bd',
    messagingSenderId: '72940076040',
    projectId: 'cool-project-collins-iregi',
    authDomain: 'cool-project-collins-iregi.firebaseapp.com',
    storageBucket: 'cool-project-collins-iregi.appspot.com',
    measurementId: 'G-VN1C1D6WST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs4sm5zJsFJtECHnUd4JTpzLrjs2e3h5M',
    appId: '1:72940076040:android:5b58cd83d8b1f89f7de5bd',
    messagingSenderId: '72940076040',
    projectId: 'cool-project-collins-iregi',
    storageBucket: 'cool-project-collins-iregi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADcz6xxAuauTHdwAhpE5L0F8CDPFO04a0',
    appId: '1:72940076040:ios:a15f929269e7f7d57de5bd',
    messagingSenderId: '72940076040',
    projectId: 'cool-project-collins-iregi',
    storageBucket: 'cool-project-collins-iregi.appspot.com',
    iosClientId: '72940076040-6kfaltn7gbdqdpbncheeh8lqicicbntc.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningDart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADcz6xxAuauTHdwAhpE5L0F8CDPFO04a0',
    appId: '1:72940076040:ios:a15f929269e7f7d57de5bd',
    messagingSenderId: '72940076040',
    projectId: 'cool-project-collins-iregi',
    storageBucket: 'cool-project-collins-iregi.appspot.com',
    iosClientId: '72940076040-6kfaltn7gbdqdpbncheeh8lqicicbntc.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningDart',
  );
}
